### ISSUE TITLE
Can't delete resources and CRD after delete replika pod

### ISSUE THREAD

**Issue by ialejandro** [prosimcorp/replika#1]
#### Issue description

I've an issue when I tried to delete some `replika.replika.prosimcorp.com` resource or `replikas.replika.prosimcorp.com` CRD, execution is waiting indefinitely after delete `replika` pod.

#### Steps to reproduce the issue

1. Delete `replika` pod
2. Delete `replika.replika.prosimcorp.com` resource

```bash
> kubectl get replikas                      
NAME                 READY   STATUS         AGE
middleware-grafana   True    SourceSynced   5m40s

> kubectl get deployment
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
replika   1/1     1            1           17m

> kubectl delete deployment replika                    
deployment.apps "replika" deleted

> kubectl delete replikas middleware-grafana           
replika.replika.prosimcorp.com "middleware-grafana" deleted
(waiting...)

or

> kubectl delete crd replikas.replika.prosimcorp.com
customresourcedefinition.apiextensions.k8s.io "replikas.replika.prosimcorp.com" deleted
(waiting...)

> kubectl -n kube-system logs -f kube-apiserver-minikube
...
E0329 08:27:03.915654       1 crd_finalizer.go:299] replikas.replika.prosimcorp.com failed with: timed out waiting for the condition
```

#### What's the expected result?

* Delete `replika.replika.prosimcorp.com` resource

#### What's the actual result?

* Can't deleted resource, it's waiting indefinitely

#### Additional details / screenshot

```bash
* Kubernetes version: v1.22.3 on Docker 20.10.8
* Minikube version: v1.24.0 (76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b)
```

**Comment by achetronic** [comment]
Hello @ialejandro
The behavior you describe is done in purpose, let me explain it deeper.

Due to Replika controller can act through namespaces, it is mandatory to take the ownership of each resource it replicates, so if you delete the controller (which is basically who deletes the targets when a Replika CR is deleted), Kubernetes can't do anything because its garbage collector is not seeing any orphan resource.

As a summary, Replika can replicate across namespaces, so it can not use the `ownerReference` to let Kubernetes clean the resources, then Replika has to clean them.

https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications

As a solution, if you redeploy Replika controller, it will take the ownership of the previous Replika CRs, so you can delete the CRs and then delete the operator.

**Comment by ialejandro** [comment]
@achetronic oh, thanks! I understand.

Regards :)
